### ISSUE TITLE
Add steps to mount in the doc

### ISSUE THREAD

**Issue by asabya** [datafund/fairos-fuse#101]

**Comment by asabya** [comment]
![image](https://user-images.githubusercontent.com/15252513/207557854-94d0461c-bc69-40eb-ba89-ea8994aca076.png)

The changes are available [here](https://github.com/datafund/fairos-fuse/blob/misc.8/docs/index.md#faq)

@crtahlin

**Comment by tfius** [comment]
we could add "create pod" if no pods are available ?

**Comment by asabya** [comment]
> we could add "create pod" if no pods are available ?

I have added it in the that branch already
