### ISSUE TITLE
Preference change makes the app un-usable 

### ISSUE THREAD

**Issue by asabya** [datafund/fairos-fuse#106]
- Start the app
- Login
- Change the batchID
- Info says "preferences changed"
- Try to mount says "User not logged in"
- Logout says "User not logged in"

**Comment by tfius** [comment]
hmm, localhost / fdp-play settings ?

**Comment by tfius** [comment]
got it, user is logged out, but UI does not reflect the changes accordingly.

**Comment by tfius** [comment]
mayne for batchid changes we do not need to force logout

**Comment by asabya** [comment]
User should be logged-out in any preference change other than mount point. The config change will start another instance of fairOS-dfs where the old session-id that is saved in handler becomes invalid.

So we create a flag `userLoggedIn`, if any config change happens, we do logout, pod = [] before saving the config.
