### ISSUE TITLE
After unsuccesfull login, user can not return

### ISSUE THREAD

**Issue by tfius** [datafund/fairos-fuse#65]
![image](https://user-images.githubusercontent.com/1674145/204859289-e60be724-c502-428e-9f3b-741a75372b06.png)

When user tries to login, and login fails with error message, such as "CIPHERTEXT BLOCK SIZE IS TOO SHORT", interface is stalled and user has no option to retry login unless restarts the app

**Comment by asabya** [comment]
Most probably login was successful, but podList failed. If we do not hide login screen until podList is successful, it might be resolved. adding this fix as I'm unable to reproduce.
