### ISSUE TITLE
gh-action mac build does not seem to run

### ISSUE THREAD

**Issue by asabya** [datafund/fairos-fuse#74]
![telegram-cloud-photo-size-4-5796403037533748257-x](https://user-images.githubusercontent.com/15252513/205651897-24e25536-2766-4940-bf08-3e734fa715de.jpg)

**Comment by tamas6** [comment]
Intel based 2017MBP

**Comment by asabya** [comment]
@tamas6 Please check if binaries from this [release](https://github.com/datafund/fairos-fuse/releases/tag/v0.1.0-rc3) work

**Comment by tamas6** [comment]
> @tamas6 Please check if binaries from this [release](https://github.com/datafund/fairos-fuse/releases/tag/v0.1.0-rc3) work

https://github.com/datafund/fairos-fuse/actions/runs/3623436054
.dmg works so far
