### ISSUE TITLE
Pod's name doesn't appear on macFUSE volume

### ISSUE THREAD

**Issue by tamas6** [datafund/fairos-fuse#80]
<img width="702" alt="Screenshot 2022-12-06 at 22 47 40" src="https://user-images.githubusercontent.com/81620050/206030236-f865bd4c-e882-4a09-89f9-afb7d1a59a74.png">

**Comment by asabya** [comment]
Thanks for noticing this. Fixed in [v0.1.0-rc4](https://github.com/datafund/fairos-fuse/releases/tag/v0.1.0-rc4)
![image](https://user-images.githubusercontent.com/15252513/206213241-708d9b3f-de8b-42f1-8427-da323ac1e5d8.png)
