### ISSUE TITLE
Automount is rapsodic at best

### ISSUE THREAD

**Issue by tamas6** [datafund/fairos-fuse#82]
![Screenshot 2022-12-07 at 12 57 05](https://user-images.githubusercontent.com/81620050/206173654-15115024-f210-4296-bc8c-63434497bf2c.png)

(tested on MBP 2017 MacOs Ventura 13.0.1)

**Comment by crtahlin** [comment]
@tamas6 what is meant by this issue? What is the issue and what would be expected?

**Comment by tamas6** [comment]
> @tamas6 what is meant by this issue? What is the issue and what would be expected?

It was about when I logged out it didn't automount after login again but latter release fixed this. So this is irrelevant !

**Comment by tfius** [comment]
automount will give us headache when multiple accounts come in. We shall disable this option for now.
