### ISSUE TITLE
style this to toggle switch, corrrect grammar

### ISSUE THREAD

**Issue by tamas6** [datafund/fairos-fuse#83]
![Screenshot 2022-12-07 at 14 17 11](https://user-images.githubusercontent.com/81620050/206189148-d81a705c-8782-44a6-883d-f9a05472cb44.png)

make it: 
## Set (bee) node address:
LOCAL -- GATEWAY

local should inadvertedly bee aware that sth is going on at ::1633, and paste address in advance
thoughts?

**Comment by tfius** [comment]
this is not the same thing. local or gateway is one thing, running something behind proxy is a different thing.

**Comment by tamas6** [comment]
>  thanks I wasn't aware. So I think default setting should bee e.g. http://localhost:1633 and switched to NO as it is

**Comment by tfius** [comment]
yes, still we will leave option to connect to bee via proxy for now.
