### ISSUE TITLE
After successful login - it is unclear what [File -> Accounts] is supposed to do or show?

### ISSUE THREAD

**Issue by rampall** [datafund/fairos-fuse#90]
![image](https://user-images.githubusercontent.com/520570/206875406-50e9abeb-fd37-4564-89f0-c7e9a36cf324.png)

**Comment by tfius** [comment]
We should add text to dialog and tell how they can add accounts to list

**Comment by tfius** [comment]
added in https://github.com/datafund/fairos-fuse/pull/102
